// ============================================
// Core: 강의 관리 기능 - 샘플 데이터
// ============================================

import { Course } from './types';

export const SAMPLE_COURSES: Course[] = [
  {
    id: '1',
    title: 'React 완전 정복',
    instructor: '김강사',
    category: '프론트엔드',
    level: 'intermediate',
    status: 'published',
    price: 49000,
    duration: 1200,
    students: 1250,
    rating: 4.8,
    thumbnail: '/images/react-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 30),
    updatedAt: new Date(Date.now() - 86400000 * 2),
  },
  {
    id: '2',
    title: 'Node.js 백엔드 마스터',
    instructor: '이강사',
    category: '백엔드',
    level: 'advanced',
    status: 'published',
    price: 69000,
    duration: 1800,
    students: 890,
    rating: 4.7,
    thumbnail: '/images/nodejs-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 45),
    updatedAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: '3',
    title: 'Python 데이터 분석实战',
    instructor: '박강사',
    category: '데이터사이언스',
    level: 'beginner',
    status: 'published',
    price: 59000,
    duration: 900,
    students: 2100,
    rating: 4.9,
    thumbnail: '/images/python-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 60),
    updatedAt: new Date(Date.now() - 86400000 * 1),
  },
  {
    id: '4',
    title: 'TypeScript 고급 패턴',
    instructor: '최강사',
    category: '프론트엔드',
    level: 'advanced',
    status: 'draft',
    price: 0,
    duration: 600,
    students: 0,
    rating: 0,
    thumbnail: '/images/typescript-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 7),
    updatedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: '5',
    title: 'AWS 클라우드 인프라 구축',
    instructor: '정강사',
    category: '인프라',
    level: 'intermediate',
    status: 'pending',
    price: 79000,
    duration: 1500,
    students: 0,
    rating: 0,
    thumbnail: '/images/aws-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 14),
    updatedAt: new Date(Date.now() - 86400000 * 10),
  },
  {
    id: '6',
    title: 'Vue.js 3.x 프로젝트',
    instructor: '강강사',
    category: '프론트엔드',
    level: 'intermediate',
    status: 'published',
    price: 45000,
    duration: 1000,
    students: 680,
    rating: 4.6,
    thumbnail: '/images/vue-course.jpg',
    createdAt: new Date(Date.now() - 86400000 * 90),
    updatedAt: new Date(Date.now() - 86400000 * 15),
  },
];

export const CATEGORIES = ['프론트엔드', '백엔드', '데이터사이언스', '인프라'];
